---

  - name: 3.3.1 Ensure IPv6 router advertisements are not accepted (Not Scored)
    sysctl:
      name: "{{ item }}"
      value: 0
      sysctl_set: True
      state: present
    with_items:
      - net.ipv6.conf.all.accept_ra
      - net.ipv6.conf.default.accept_ra 
    tags:
      - section3
      - section3.3
      - section3.3.1

  - name: 3.3.2 Ensure IPv6 redirects are not accepted (Not Scored)
    sysctl:
      name: "{{ item }}"
      value: 0
      sysctl_set: True
      state: present
    with_items:
      - net.ipv6.conf.default.accept_redirects
      - net.ipv6.conf.all.accept_redirects
    tags:
      - section3
      - section3.3
      - section3.3.2

  - name: 3.3.3 Ensure IPv6 is disabled (Not Scored)
    lineinfile:
      dest: /etc/default/grub
      line: "GRUB_CMDLINE_LINUX='ipv6.disable=1'"
    when: disable_ipv6 == True
    tags:
      - section3
      - section3.3
      - section3.3.3
