---

  - name: 3.1.1 Ensure IP forwarding is disabled (Scored)
    sysctl:
      name: net.ipv4.ip_forward
      value: '{{net_ipv4_ip_forward}}'
      state: present
    tags:
      - section3
      - section3.1
      - section3.1.1

  - name: 3.1.2 Ensure packet redirect sending is disabled (Scored)
    sysctl:
      name: "{{ item }}"
      value: 0
      sysctl_set: True
      state: present
    with_items:
      - net.ipv4.conf.all.send_redirects
      - net.ipv4.conf.default.send_redirects
    tags:
      - section3
      - section3.1
      - section3.1.2
