Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
	ansible.inventory_path = "./hosts"
    ansible.verbose = "-vvv"
    ansible.limit = "all"
    ansible.host_key_checking = false
  end
end
